version: '3.8'

services:
  dome-position:
    build: .
    container_name: dome-position
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    command: sh -c "python import_csv.py && python import_daycsv.py && python server.py 8080"
    restart: unless-stopped
